# Generated by Django 4.2.13 on 2026-01-17 18:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0030_customuser_administracao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nivels',
            new_name='niveis',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='Telefone',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='Utente',
            new_name='utente',
        ),
        migrations.RenameField(
            model_name='seccoes',
            old_name='Departamento',
            new_name='departamento',
        ),
        migrations.AlterUniqueTogether(
            name='seccoes',
            unique_together={('nome', 'departamento')},
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='Entidade',
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo_digitalizado',
            field=models.FileField(blank=True, null=True, upload_to='digitalizados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='seccoes',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seccao_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
