# Generated by Django 4.2.13 on 2026-01-17 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0031_rename_nivels_documento_niveis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='telefone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'O telefone deve ter 9 dígitos.')]),
        ),
    ]
