# Generated by Django 4.2.13 on 2026-01-17 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0032_alter_documento_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('criacao', 'Criação'), ('recebimento', 'Recebimento'), ('encaminhamento', 'Encaminhamento'), ('despacho', 'Despacho'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('arquivado', 'Arquivado')], default='encaminhamento', max_length=20),
        ),
    ]
