# Generated by Django 4.2.11 on 2026-01-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0037_documento_administracao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nome', 'administracao')},
        ),
    ]
