# Generated by Django for data migration
from django.db import migrations


def populate_orphan_administracoes(apps, schema_editor):
    """
    Migra registros órfãos (sem administração) para a primeira administração compatível.
    
    Lógica:
    1. Departamentos genéricos (sem admin): Atribui à primeira admin do mesmo tipo_municipio
    2. Usuários sem admin: Herda a admin do departamento
    3. Documentos sem admin: Herda a admin do criador ou departamento_origem
    """
    Administracao = apps.get_model('ARQUIVOS', 'Administracao')
    Departamento = apps.get_model('ARQUIVOS', 'Departamento')
    CustomUser = apps.get_model('ARQUIVOS', 'CustomUser')
    Documento = apps.get_model('ARQUIVOS', 'Documento')
    
    # Cache de administrações por tipo
    admins_por_tipo = {}
    for admin in Administracao.objects.all():
        if admin.tipo_municipio not in admins_por_tipo:
            admins_por_tipo[admin.tipo_municipio] = admin
    
    # NOVO: Criar admins padrão para cada tipo se não existirem
    # Isso é necessário para bancos de dados novos (ex: testes)
    # [COMENTADO] Administrações padrão não são mais necessárias após população completa
    # for tipo in ['A', 'B', 'C', 'D', 'E']:
    #     if tipo not in admins_por_tipo:
    #         admin_padrao, created = Administracao.objects.get_or_create(
    #             tipo_municipio=tipo,
    #             defaults={'nome': f'Administração Padrão Tipo {tipo}'}
    #         )
    #         admins_por_tipo[tipo] = admin_padrao
    #         if created:
    #             print(f"  [CREATED] Admin padrão Tipo {tipo}")
    
    # 1. Migrar Departamentos órfãos
    dept_orfaos = Departamento.objects.filter(administracao__isnull=True)
    for dept in dept_orfaos:
        admin_compativel = admins_por_tipo.get(dept.tipo_municipio)
        if admin_compativel:
            dept.administracao = admin_compativel
            dept.save(update_fields=['administracao'])
            print(f"  [DEPT] {dept.nome} -> {admin_compativel.nome}")
        else:
            print(f"  [WARN] Departamento {dept.id} sem admin compatível (Tipo {dept.tipo_municipio})")
    
    # 2. Migrar Usuários órfãos
    users_orfaos = CustomUser.objects.filter(administracao__isnull=True)
    for user in users_orfaos:
        # Tenta herdar do departamento
        if user.departamento and user.departamento.administracao:
            user.administracao = user.departamento.administracao
            user.save(update_fields=['administracao'])
            print(f"  [USER] {user.username} -> {user.administracao.nome}")
        else:
            # Fallback: primeira administração
            first_admin = Administracao.objects.first()
            if first_admin:
                user.administracao = first_admin
                user.save(update_fields=['administracao'])
                print(f"  [USER] {user.username} -> {first_admin.nome} (fallback)")
    
    # 3. Migrar Documentos órfãos
    docs_orfaos = Documento.objects.filter(administracao__isnull=True)
    for doc in docs_orfaos:
        admin = None
        
        # Prioridade 1: Admin do criador
        if doc.criado_por and hasattr(doc.criado_por, 'administracao') and doc.criado_por.administracao:
            admin = doc.criado_por.administracao
        # Prioridade 2: Admin do departamento de origem
        elif doc.departamento_origem and doc.departamento_origem.administracao:
            admin = doc.departamento_origem.administracao
        # Prioridade 3: Admin do departamento atual
        elif doc.departamento_atual and doc.departamento_atual.administracao:
            admin = doc.departamento_atual.administracao
        
        if admin:
            doc.administracao = admin
            doc.save(update_fields=['administracao'])
            print(f"  [DOC] {doc.numero_protocolo} -> {admin.nome}")
        else:
            print(f"  [WARN] Documento {doc.id} sem admin identificável")


def reverse_populate(apps, schema_editor):
    """Reverter a migration: remove administrações atribuídas"""
    # Não fazemos nada - perda de dados não é reversível de forma segura
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ARQUIVOS', '0038_add_unique_together_departamento'),
    ]

    operations = [
        migrations.RunPython(populate_orphan_administracoes, reverse_populate),
    ]
